"use strict";
let userName = prompt ("What is your name?");
alert (userName);
console.log ("name:", userName);
let a = 5;
let b = 2;
let sum = a + b;
alert (sum);
console.log (sum);
let subtraction = a - b;
alert (subtraction);
console.log (subtraction);
let multiplication = a * b;
alert (multiplication);
console.log (multiplication);
let division = a / b;
alert (division);
console.log (division);
let exponentiation = a ** b;
alert (exponentiation);
console.log (exponentiation);